/*
    Copyright (C) 2014 Samsung Electronics.

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB. If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

[
    Conditional=TIZEN_MEDIA_STREAM,
    NoInterfaceObject,
    ImplementationLacksVTable
] interface CameraError {
    readonly attribute unsigned short code;
    const unsigned short CREATION_FAILED = 0;
    const unsigned short PERMISSION_DENIED = 1;
    const unsigned short NO_CAMERA = 2;
    const unsigned short PIPELINE_ERR = 3;
    const unsigned short FILE_WRITE_ERR = 4;
};
