# - Try to find WIDGETSERVICE

include(FindPkgConfig)

pkg_check_modules(WIDGETSERVICE_PKGCONF libwidget_service)

find_path(WIDGETSERVICE_INCLUDE_DIRS
    NAMES widget_service/widget_buffer.h
    PATHS ${WIDGETSERVICE_PKGCONF_INCLUDE_DIRS}
)

find_library(WIDGETSERVICE_LIBRARIES
    NAMES widget_service
    PATHS ${WIDGETSERVICE_PKGCONF_LIBRARY_DIRS}
)

# set(WIDGETSERVICE_PROCESS_INCLUDES WIDGETSERVICE_INCLUDE_DIR WIDGETSERVICE_INCLUDE_DIRS)
# set(WIDGETSERVICE_PROCESS_LIBS WIDGETSERVICE_LIBRARY WIDGETSERVICE_LIBRARIES)
# libfind_process(WIDGETSERVICE)


include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WIDGETSERVICE DEFAULT_MSG WIDGETSERVICE_INCLUDE_DIRS)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WIDGETSERVICE DEFAULT_MSG WIDGETSERVICE_LIBRARIES)
