# - Try to find smack
# Once done, this will define
#
#  LIBSMACK_FOUND - system has libsmack
#  LIBSMACK_INCLUDE_DIRS - the libsmack include directories
#  LIBSMACK_LIBRARIES - link these to use libsmack

INCLUDE(FindPkgConfig)

PKG_CHECK_MODULES(PC_LIBSMACK libsmack)

FIND_PATH(LIBSMACK_INCLUDE_DIRS NAMES sys/smack.h
    HINTS ${PC_LIBSMACK_INCLUDE_DIRS} ${PC_LIBSMACK_INCLUDEDIR}
)

FIND_LIBRARY(LIBSMACK_LIBRARIES NAMES smack
    HINTS ${PC_LIBSMACK_LIBRARY_DIRS} ${PC_LIBSMACK_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBSMACK DEFAULT_MSG LIBSMACK_INCLUDE_DIRS LIBSMACK_LIBRARIES)
