# - Try to find ewebkit2-ext
# Once done, this will define
#
#  DRI2_FOUND - system has DRI2_INFO
#  DRI2_INCLUDE_DIRS - the DRI2 include directories
#  DRI2_LIBRARIES - link these to use DRI2_INFO

INCLUDE(FindPkgConfig)

PKG_CHECK_MODULES(DRI2
    libdri2
)

FIND_PATH(DRI2_INCLUDE_DIRS NAMES dri2.h
HINTS ${DRI2_INCLUDE_DIRS} ${DRI2_INCLUDEDIR}
)

FIND_LIBRARY(DRI2_LIBRARIES NAMES libdri2
HINTS ${DRI2_LIBRARY_DIRS} ${DRI2_LIBDIR}
)

SET(DRI2_INCLUDE_DIRS
${DRI2_INCLUDE_DIRS}
)

SET(DRI2_LIBRARIES
${DRI2_LIBRARIES}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DRI2 DEFAULT_MSG DRI2_INCLUDE_DIRS)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DRI2 DEFAULT_MSG DRI2_LIBRARIES)

