# -Try to find MMSOUND
# Once done, this will define
#
#  MMSOUND_FOUND - system has mm-sound
#  MMSOUND_INCLUDE_DIRS - the mm-sound include directories
#  MMSOUND_LIBRARIES - link these to use mm-sound

INCLUDE(FindPkgConfig)

PKG_CHECK_MODULES(MMSOUND
    mm-sound
)

FIND_PATH(MMSOUND_INCLUDE_DIRS NAMES mm_sound.h
    HINTS ${MMSOUND_INCLUDE_DIRS} ${MMSOUND_INCLUDEDIR}
)
FIND_LIBRARY(MMSOUND_LIBRARIES NAMES mm-sound
    HINTS ${MMSOUND_LIBRARY_DIRS} ${MMSOUND_LIBDIR}
)

SET(MMSOUND_INCLUDE_DIRS
    ${MMSOUND_INCLUDE_DIRS}
)
SET(MMSOUND_LIBRARIES
    ${MMSOUND_LIBRARIES}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MMSOUND DEFAULT_MSG MMSOUND_INCLUDE_DIRS MMSOUND_LIBRARIES)
