# - Try to find STT

include(FindPkgConfig)

pkg_check_modules(STT_PKGCONF stt)

find_path(STT_INCLUDE_DIRS
    NAMES stt.h
    PATHS ${STT_PKGCONF_INCLUDE_DIRS}
)

find_library(STT_LIBRARIES
    NAMES stt
    PATHS ${STT_PKGCONF_LIBRARY_DIRS}
)

# set(STT_PROCESS_INCLUDES STT_INCLUDE_DIR STT_INCLUDE_DIRS)
# set(STT_PROCESS_LIBS STT_LIBRARY STT_LIBRARIES)
# libfind_process(STT)


include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STT DEFAULT_MSG STT_INCLUDE_DIRS)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STT DEFAULT_MSG STT_LIBRARIES)
