list(APPEND JavaScriptCore_INCLUDE_DIRECTORIES
    ${ECORE_INCLUDE_DIRS}
    ${EINA_INCLUDE_DIRS}
    ${EO_INCLUDE_DIRS}
)

set(JavaScriptCore_API_HEADERS
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JSBase.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JSContextRef.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JSObjectRef.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JSStringRef.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JSStringRefBSTR.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JSStringRefCF.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JSValueRef.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JavaScript.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/JavaScriptCore.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/API/WebKitAvailability.h"
)

INSTALL(FILES ${JavaScriptCore_API_HEADERS}
        DESTINATION include/${WebKit2_OUTPUT_NAME}-${PROJECT_VERSION_MAJOR}/JavaScriptCore)
