#ifndef TIZEN_H
#define TIZEN_H

#define ENABLE(TIZEN_FEATURE) (defined ENABLE_##TIZEN_FEATURE  && ENABLE_##TIZEN_FEATURE)

#define ENABLE_TIZEN_TLS11_AND_TLS12_SUPPORT_DISABLE 0

#define ENABLE_TIZEN_NPN 1

#endif
